development:
  adapter: postgresql
  encoding: unicode
  database: ace_editor_embed_test_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ace_editor_embed_test_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ace_editor_embed_test_production
  pool: 5